proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  hide-navbar: true
  landing_page: /app/01_donations
  users:
  - name: stary
    password: password
    groups: admins
  - name: kosma
    password: password
  - name: damian
    password: password
  docker:
      internal-networking: true
  specs:
  - id: 01_donations
    display-name: Darowizny
    description: Analiza struktury darowizn
    container-cmd: ["R", "-e", "shiny::runApp('/root/app', port = 3838, host = '0.0.0.0')"]
    container-image: aczepielik/donations:latest
    container-network: donationsbridge

logging:
  file:
    shinyproxy.log